version: '3'
services:
  web:
    build: ./web-container
    container_name: sp-web
    ports:
      - '80:80'
    volumes:
      - ./web-src:/www
      - ./data/wp-uploads:/www/wp-content/uploads
      #- ./log:/var/log
    links:
      - db
    restart: always
  db:
    image: mysql
    container_name: sp-db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always
  dev:
    build: ./dev-container
    container_name: sp-dev
    volumes:
      - ./web-src:/www
    links:
      - db