version: '3'
services:
  web:
    build: ./web-container
    container_name: subprocess-web
    ports:
      - '80:80'
    volumes:
      - ./web-src:/www
    links:
      - db
  db:
    image: mysql
    container_name: subprocess-db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'